package com.mybatis.bean;

import java.math.BigDecimal;

public class Customers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.customerNumber
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private Integer customernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.customerName
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.contactLastName
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private String contactlastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.contactFirstName
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private String contactfirstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.phone
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.addressLine1
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private String addressline1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.addressLine2
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private String addressline2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.city
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.state
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.postalCode
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private String postalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.country
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.salesRepEmployeeNumber
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private Integer salesrepemployeenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.creditLimit
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    private BigDecimal creditlimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.customerNumber
     *
     * @return the value of customers.customerNumber
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public Integer getCustomernumber() {
        return customernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.customerNumber
     *
     * @param customernumber the value for customers.customerNumber
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setCustomernumber(Integer customernumber) {
        this.customernumber = customernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.customerName
     *
     * @return the value of customers.customerName
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.customerName
     *
     * @param customername the value for customers.customerName
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setCustomername(String customername) {
        this.customername = customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.contactLastName
     *
     * @return the value of customers.contactLastName
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public String getContactlastname() {
        return contactlastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.contactLastName
     *
     * @param contactlastname the value for customers.contactLastName
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setContactlastname(String contactlastname) {
        this.contactlastname = contactlastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.contactFirstName
     *
     * @return the value of customers.contactFirstName
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public String getContactfirstname() {
        return contactfirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.contactFirstName
     *
     * @param contactfirstname the value for customers.contactFirstName
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setContactfirstname(String contactfirstname) {
        this.contactfirstname = contactfirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.phone
     *
     * @return the value of customers.phone
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.phone
     *
     * @param phone the value for customers.phone
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.addressLine1
     *
     * @return the value of customers.addressLine1
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public String getAddressline1() {
        return addressline1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.addressLine1
     *
     * @param addressline1 the value for customers.addressLine1
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.addressLine2
     *
     * @return the value of customers.addressLine2
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public String getAddressline2() {
        return addressline2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.addressLine2
     *
     * @param addressline2 the value for customers.addressLine2
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.city
     *
     * @return the value of customers.city
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.city
     *
     * @param city the value for customers.city
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.state
     *
     * @return the value of customers.state
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.state
     *
     * @param state the value for customers.state
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.postalCode
     *
     * @return the value of customers.postalCode
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.postalCode
     *
     * @param postalcode the value for customers.postalCode
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.country
     *
     * @return the value of customers.country
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.country
     *
     * @param country the value for customers.country
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.salesRepEmployeeNumber
     *
     * @return the value of customers.salesRepEmployeeNumber
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public Integer getSalesrepemployeenumber() {
        return salesrepemployeenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.salesRepEmployeeNumber
     *
     * @param salesrepemployeenumber the value for customers.salesRepEmployeeNumber
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setSalesrepemployeenumber(Integer salesrepemployeenumber) {
        this.salesrepemployeenumber = salesrepemployeenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.creditLimit
     *
     * @return the value of customers.creditLimit
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public BigDecimal getCreditlimit() {
        return creditlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.creditLimit
     *
     * @param creditlimit the value for customers.creditLimit
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    public void setCreditlimit(BigDecimal creditlimit) {
        this.creditlimit = creditlimit;
    }
}