server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/classicmodels?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    #pattern prefix
    static-path-pattern: /static/**
  resources:
    #the truly location of js and css
    static-locations[0]: classpath:/static/

mybatis:
  mapper-locations: classpath:mapper/*.xml  # where the xml stays
  type-aliases-package: com.mybatis.bean  # the package of bean
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
logging:
  config: classpath:log4j2.xml
