package com.mybatis.dao;

import com.mybatis.bean.Offices;
import com.mybatis.bean.OfficesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfficesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    int countByExample(OfficesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    int deleteByExample(OfficesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    int deleteByPrimaryKey(String officecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    int insert(Offices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    int insertSelective(Offices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    List<Offices> selectByExample(OfficesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    Offices selectByPrimaryKey(String officecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") Offices record, @Param("example") OfficesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    int updateByExample(@Param("record") Offices record, @Param("example") OfficesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    int updateByPrimaryKeySelective(Offices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offices
     *
     * @mbggenerated Thu Mar 12 10:52:35 CST 2020
     */
    int updateByPrimaryKey(Offices record);
}